<?php

namespace PaBundle\Repository;

/**
 * DependentCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependentCandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
