<?php

namespace PaBundle\Repository;

/**
 * IndependentCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndependentCandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
