<?php

namespace PaBundle\Repository;

/**
 * PaCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaCandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
