<?php

namespace PaBundle\Repository;

/**
 * PaComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaComplaintRepository extends \Doctrine\ORM\EntityRepository
{
}
