<?php

namespace PaBundle\Repository;

/**
 * PaEditedVoteCastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaEditedVoteCastRepository extends \Doctrine\ORM\EntityRepository
{
}
