<?php

namespace PaBundle\Repository;

/**
 * PaFootPrintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaFootPrintRepository extends \Doctrine\ORM\EntityRepository
{
}
