<?php

namespace PaBundle\Repository;

/**
 * PaNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
