<?php

namespace PaBundle\Repository;

/**
 * PaPartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaPartyRepository extends \Doctrine\ORM\EntityRepository
{
}
