<?php

namespace PaBundle\Repository;

/**
 * PaPinkSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaPinkSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
