<?php

namespace PaBundle\Repository;

/**
 * PaVoteCastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaVoteCastRepository extends \Doctrine\ORM\EntityRepository
{
}
