<?php

namespace PrBundle\Repository;

/**
 * PrComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrComplaintRepository extends \Doctrine\ORM\EntityRepository
{
}
