<?php

namespace PrBundle\Repository;

/**
 * PrDependentCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrDependentCandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
