<?php

namespace PrBundle\Repository;

/**
 * PrEditedVoteCastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrEditedVoteCastRepository extends \Doctrine\ORM\EntityRepository
{
}
