<?php

namespace PrBundle\Repository;

/**
 * PrFootPrintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrFootPrintRepository extends \Doctrine\ORM\EntityRepository
{
}
