<?php

namespace PrBundle\Repository;

/**
 * PrIndependentCandidateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrIndependentCandidateRepository extends \Doctrine\ORM\EntityRepository
{
}
