<?php

namespace PrBundle\Repository;

/**
 * PrNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
