<?php

namespace PrBundle\Repository;

/**
 * PrPartyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrPartyRepository extends \Doctrine\ORM\EntityRepository
{
}
