<?php

namespace PrBundle\Repository;

/**
 * PrPinkSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrPinkSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
