<?php

namespace PrBundle\Repository;

/**
 * PrVoteCastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrVoteCastRepository extends \Doctrine\ORM\EntityRepository
{
}
