<?php

namespace UserBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOnlineUsers($numberPerPage, $page)
    {
        $query = $this->createQueryBuilder('u');
        if($page < 1){
            throw new \InvalidArgumentException('The argument   $page cannot be negative. Value: '.$page);
        }
        
        $query->setFirstResult(($page - 1)*$numberPerPage)
              ->where('u.active = :var')
              ->setParameter('var', true)
              ->setMaxResults($numberPerPage);
        
        return new Paginator($query);
        
        /*$queryBuilder = $this->createQueryBuilder('u');
        $queryBuilder->where('u.active = :var')
                     ->setParameter('var', true);
        $result = $queryBuilder->getQuery()->getResult();
        
        return $result;*/
    }
}
