<?php

namespace Proxies\__CG__\VtallyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Constituency extends \VtallyBundle\Entity\Constituency implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'id', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'name', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'code', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'pollingStations', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'dependentCandidates', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'independentCandidates', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'region', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'collationCenter'];
        }

        return ['__isInitialized__', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'id', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'name', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'code', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'pollingStations', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'dependentCandidates', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'independentCandidates', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'region', '' . "\0" . 'VtallyBundle\\Entity\\Constituency' . "\0" . 'collationCenter'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Constituency $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getWinner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWinner', []);

        return parent::getWinner();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addPollingStation(\VtallyBundle\Entity\PollingStation $pollingStation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPollingStation', [$pollingStation]);

        return parent::addPollingStation($pollingStation);
    }

    /**
     * {@inheritDoc}
     */
    public function removePollingStation(\VtallyBundle\Entity\PollingStation $pollingStation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePollingStation', [$pollingStation]);

        return parent::removePollingStation($pollingStation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPollingStations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPollingStations', []);

        return parent::getPollingStations();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(\VtallyBundle\Entity\Region $region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$region]);

        return parent::setRegion($region);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollationCenter(\VtallyBundle\Entity\CollationCenter $collationCenter = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollationCenter', [$collationCenter]);

        return parent::setCollationCenter($collationCenter);
    }

    /**
     * {@inheritDoc}
     */
    public function getCollationCenter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollationCenter', []);

        return parent::getCollationCenter();
    }

    /**
     * {@inheritDoc}
     */
    public function addDependentCandidate(\PaBundle\Entity\DependentCandidate $dependentCandidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDependentCandidate', [$dependentCandidate]);

        return parent::addDependentCandidate($dependentCandidate);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDependentCandidate(\PaBundle\Entity\DependentCandidate $dependentCandidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDependentCandidate', [$dependentCandidate]);

        return parent::removeDependentCandidate($dependentCandidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependentCandidates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependentCandidates', []);

        return parent::getDependentCandidates();
    }

    /**
     * {@inheritDoc}
     */
    public function addIndependentCandidate(\PaBundle\Entity\IndependentCandidate $independentCandidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndependentCandidate', [$independentCandidate]);

        return parent::addIndependentCandidate($independentCandidate);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIndependentCandidate(\PaBundle\Entity\IndependentCandidate $independentCandidate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIndependentCandidate', [$independentCandidate]);

        return parent::removeIndependentCandidate($independentCandidate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndependentCandidates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndependentCandidates', []);

        return parent::getIndependentCandidates();
    }

}
