<?php

namespace VtallyBundle\Repository;

/**
 * CollationCenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollationCenterRepository extends \Doctrine\ORM\EntityRepository
{
}
