<?php

namespace VtallyBundle\Repository;

/**
 * ConstituencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstituencyRepository extends \Doctrine\ORM\EntityRepository
{
}
