<?php

namespace VtallyBundle\Repository;

/**
 * ReturningOfficerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReturningOfficerRepository extends \Doctrine\ORM\EntityRepository
{
}
